version: "3.8"
services:

  phoenix:
    environment:
      - DEBUG=TRUE
      - S3_HOST=localhost
      - MEDIA_HOST=localhost:8001

  admin:
    environment:
      - SERVER_URL=http://127.0.0.1:4000

  traefik:
    ports:
      - "8000:80"
      - "8008:8080"
