# Local dev environment

version: "3.8"
services:
  # server
  blogsley:
    build:
      context: ./server
      target: dev
    depends_on:
      - blogsley-pg
      #- blogsley-s3
      #- blogsley-dps
    environment:
      - DEBUG=TRUE
      - BLOGSLEY_SECRET_KEY=${BLOGSLEY_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - S3_HOST=${S3_HOST}
    ports:
      - 8000:4000
    networks:
      - blogsley
    restart: "no"
    volumes:
      - "./server:/app"

  pgAdmin:
    image: dpage/pgadmin4
    depends_on:
      - blogsley-pg
    restart: always
    ports:
        - "8888:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: 1234@admin.com
        PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
        - ./volumes/pgadmin:/var/lib/pgadmin4/storage
    networks:
      - blogsley

  # Database
  blogsley-pg:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: "no"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    networks:
      - blogsley
  

  # Front-end
  blogsley-admin:
    build:
      # context: admin
      context: ./admin
      target: quasar-dev
    ports:
      - 8080:8080
    restart: "no"
    volumes:
      - "./admin:/admin"

networks:
  blogsley: